name: Go CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.3
      - name: Build with Go
        run: go build -o staging/alpimager main.go
      - uses: actions/upload-artifact@v1
        with:
          name: Linux Binary
          path: staging
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: unstable-linux
          files: |
            staging/*

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.3
      - name: Build with Go
        run: go build -o staging/alpimager main.go
      - uses: actions/upload-artifact@v1
        with:
          name: macOS Binary
          path: staging
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: unstable-macos
          files: |
            staging/*

  test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.3
      - name: Build with Go
        run: go build -o staging/alpimager main.go
      - name: Test
        run: cd testdata && ../staging/alpimager/alpimager -debug

  test-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.3
      - name: Set up Docker
        run: brew install docker-machine docker
      - name: Build with Go
        run: go build -o staging/alpimager main.go
      - name: Test
        run: cd testdata && ../staging/alpimager/alpimager -debug
